---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`sum_lengths` is a function"
  checked: true
- value: "`sum_lengths` has two parameters"
  checked: true
- value: "`sum_lengths` can be called with 2 arguments"
  checked: true
- value: if we write `sum_lengths("learning", "programming")`, `"learning"` will be
    the first argument and `"programming"`, the second
  checked: true
name: Functions with holes
