---
locale: en
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Yes, because in the function `is_library`, `place` is a string type parameter
    and we must indicate it by placing it in quotes
  checked: false
- value: No, because in the `is_library` function, `place` is a parameter of type
    string, but the parameters are names that are not enclosed in quotes
  checked: true
name: Hanging on a string
