---
locale: en
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Both functions start with `def`, followed by the name of the function
  checked: true
- value: Both functions start with `def`, followed by a colon
  checked: false
- value: Both functions have a `return` in the first line
  checked: false
- value: Both functions have a `return` in the last line
  checked: true
- value: Both functions end with a colon in the first line
  checked: true
- value: The second line of both functions is aligned next to the margin
  checked: false
name: Find the differences
