---
locale: en
tags: []
layout: input_bottom
editor: code
type: problem
extra_visible: true
teacher_info: ''
manual_evaluation: false
progressive_expectations: true
choices: []
name: My favorite things
